# Generated by Django 5.0.7 on 2024-07-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
